apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.order.name }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: order
spec:
  replicas: {{ .Values.order.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "backend-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/backend"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "secret/data/backend" -}}`}}
          DATABASE_URL={{`{{ .Data.data.DATABASE_URL }}`}}
          JWT_SECRET_KEY={{`{{ .Data.data.JWT_SECRET_KEY }}`}}
          RABBITMQ_URL={{`{{ .Data.data.RABBITMQ_URL }}`}}
          ENVIRONMENT={{`{{ .Data.data.ENVIRONMENT }}`}}
          ACCESS_TOKEN_EXPIRE_MINUTES={{`{{ .Data.data.ACCESS_TOKEN_EXPIRE_MINUTES }}`}}
          API_URL={{`{{ .Data.data.API_URL }}`}}
          {{`{{- end }}`}}
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: order-container
          image: {{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}
          ports:
            - containerPort: {{ .Values.order.port }}

          env:
            - name: VAULT_CONFIG_PATH
              value: /vault/secrets/config

          envFrom:
            - configMapRef:
                name: {{ .Values.configmaps.backend.name }}

          resources:
            limits:
              memory: {{ .Values.order.resources.limits.memory }}
              cpu: {{ .Values.order.resources.limits.cpu }}
            requests:
              memory: {{ .Values.order.resources.requests.memory }}
              cpu: {{ .Values.order.resources.requests.cpu }}