apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "order.labels" . | nindent 4 }}

data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}