apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order.fullname" . }}
  labels:
    {{- include "order.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "order.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "order.selectorLabels" . | nindent 8 }}

    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ include "order.serviceAccountName" . }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "order.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname

      containers:
        - name: order-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /api/v1/customer/health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/v1/customer/health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3