apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}

spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: <ENCRYPTED>
    MYSQL_DATABASE: <ENCRYPTED>
    MYSQL_USER: <ENCRYPTED>
    MYSQL_PASSWORD: <ENCRYPTED>

  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque