apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

spec:
  encryptedData:
    MYSQL_DATABASE: {{ .Values.secrets.MYSQL_DATABASE | quote }}
    MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD | quote }}
    MYSQL_ROOT_PASSWORD: {{ .Values.secrets.MYSQL_ROOT_PASSWORD | quote }}
    MYSQL_USER: {{ .Values.secrets.MYSQL_USER | quote }}
  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque