apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  serviceName: {{ .Values.name }}
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      securityContext:
        fsGroup: 999

      containers:
        - name: mysql
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        storageClassName: {{ .Values.storageClass }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storageSize }}