replicaCount: 3

image:
  repository: ghcr.io/kube-pod404/opslora-notification-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

rabbitmq:
  host: rabbitmq
  port: 5672

secretName: notification-secret

pod:
  automountServiceAccountToken: false

serviceAccount:
  create: true
  name: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

affinity:
  enabled: true
  rabbitmqPodAffinity:
    enabled: true
    weight: 50
    topologyKey: kubernetes.io/hostname
    labelKey: app
    labelValues:
      - rabbitmq
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral-storage: "500Mi"

probes:
  startup:
    enabled: false
    path: /health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readiness:
    enabled: false
    path: /health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    enabled: false
    path: /health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

secrets:
  FROM_EMAIL: AgCXiqszG9wDfCUNZ0jBXHUOCptSfj9sMR9BaygMkZcq89O69ob5EfVGsjKS8quEwQaQZqzbnahidCrCkf6XoUo9iSoXQT5Ol+dqgv2Z7KO6MWVp7FNGPKYrMODfAHXLhMP/PS/ndv0x1r/B5GWLjM+ltwgzimCS4DIlJ+R6jBTzPw4roMvsIzQzDi3NURgzHKjZUSarU1B7O+/IEEgdnZllwo81gUHL4jQ5tvG5EmQ6rO2RVrFx2g1cLjqqyP1t3MsK9u1Q2wfUmqPjdADq0DLoUHwny4uSSjXpAQ0DpgJh8a7PLQe3JjUrsohWbZdZZIdc6puPKvcfGeN7TtZAA5OgCgCBl4HlSFSbZIk4Jr4Z6az42M4PoZ7G+4KP8/mx/oUt3q/oHs64c0XRgIuEMOeWM96bVhNKrFsuozbM5b9onyg5WHlfJMrKVcxm/irhcGYwzkDKNgE9lAKe3vf/dV/9sIu24p0OZKwxA3KP36CaiKlmW1ZFCme8aHlEWIyOnkJXu/VtxOvc7f3C/bJnisRBLCjN99Bg07DjWXZFWNIMq6KT5P1th1WQtOsVkpUqfw1stIl3VHrCZZEIWc2PS58snAPr2M7fPCm/qxxiL4ySptInBXGDru7/f2B6GC8ElyX/5jbkdr35p/Jnp8gDaFZgblwA0U8pfKnkqz5ypVp1bIXsKsgLI/sWejqEe+pRcIOAaZwbg8ajSfgw6c4A4X0rv9QcOeIvZT4=
  FROM_NAME: AgAVViSBY41hAeIFvCycEVCe/MpWd6T6jn1drMdjAEbjSV72rB/VAGqJS7imtu6KiTe4p1+Wyr/YlInwhEwIsojLNK4ABqtuTvgQH2SvegbSA/bn0NAhlCT/jQnV/StAkUf5ne+WF8hGtQxYdpK89zm06PLqOp2TGyCjPLm5zRWDf+2+w/A35p97J6hySzzpJkwSPUG7w+FHRJKDXz5cL8iUeUgOGa0GEVNREM+wHeuf9ZxcUsjnk8PAka8izE2huXAjQ/dwf0kPlYKzi+dz9dfpvkcvKISFZEgfHromjmwZVSx6HLML4b9oCO/JlJpX6oXHE7jw0eATl5+dfnMC1vsBluNDCk/ZGP71tQGYLtXn+0XyLtAI6ek2k/J24MXKSuMdXwpkdNSVGeaPnIAbRttHB6bHMqAUwhnHBQxcXTjiaC3SXBEvKOVMbWoPQIcvC5kUc8D6ih3zcvQ4SEyW/H1UPQexDXshsy/KnVvy3sti+PogI3UYRrz2BZTeZ8ej2OKxVWqZfVlEv7pGL14sZhvZk+acVxxKSK+b7bavCyKL0FYbNSUzMLjqo/KHi7hNGtjNZOxYqdK69E93Dp7KLUwnGfSm1xtR7AGSZKpZigj20YeFOxGhNCiuvqBu4VTy1k3YZBlZOJ4Zh9tqRaMzTi2ApbMIjoKn5BAE6ZesPBUAf9C4wGNrOY1HqAz4sj93iDJe3XNOSAc0
  RABBITMQ_URL: AgDGd3rnEUKC5gp7jhzNpsd9aKEQvH/Hlgnw+HosHBxehmahWB6UiYphfXLehbIT4KvZ9o4l6WiP0itIQPWjioCuppspcmvr0D/jGTdlIIWbLzMnez6FajGVxwJeX7j8bwVZJL1baCHone58J5i10wLSv2z3vFv47986AuujXETWz3XPtFy85rwOE9qBC0Cr8jUD2/NnlzBp3w67EDeLrjmVEn7MXGcRw8rhvfFHv6rs34k19opSX98Iqz0Ws6PndDQtcxFzMgn0Ixbhxhgu/qyP2lttr1/jQYaba9QPXuSXQk/fab+CNRLScJ2/1ieE4BYQsAh+W6PUiSNaNjGIpxWuoCP8ITUd3IaNz2jW5pe1aOCzS7FahmGD8fTcvT4/Zy4kmA3L9PuoRJtDW32UNCf8x897INwCjQabTLHHtpvBKFCgy+B2iLoGGoejT2z6fKBvCrrRCcBf+58BSbDeaLhgrOjUuXkDSzbhZorkneH4n/NjYVv2hUmHSYpIfXP+Md4phFqTvN+6grFgYuDxjueIBCSdvIssQ9mX0JHoNEcldTWuJlVXCcB4GcF7xjXPJOCvFF3ybDO/GKOu/eA2xpfLVdYx0C4oyIBPCJqYDGVGRRnfS+ZWwqP87vDg0tpkv/cWUGLMSJ4Lq0pIA/qCgRRakyJtPloDMgUHwnjEMdYLHGhD1Ddjb6DIDSOGcVEiX9LPYPLQROYlVH66zomNdKryET3UX8XhdA13Ona9gvowflI2oZdiXZ+CwmLGG1fCu2QN
  SMTP_PASS: AgBR51akuIXk2tTnvMuszeK4T7npX0b+bvQGkqTFC0+PnTFRHUNaVXx+qz2RfGwsgZG5iwsoMXxHc5xhAcadi76+SUV4wAO+FToxPvKGGdDdV2bw3CLdCqr4ZDpK2DHN7tXgQg/IL/flxIlSwERwzQcwndBN+fpPUiGA+KWXZVdLlhYA4EX/TzaGImIJ3vRa9OQJPsiejFqUKuTDrnXnzTVnTS0U92jO09Smuue5K4/dU/UTmJg6LlS60DGcyRJV+qnPLc2lAD5e3+WObDymawW/TL8GL3E4kv6XZYlYDSUYu0AKdORNjPB58xyDzLjWWUot/CNMU/b/sxCw473Os4Jc5ZUOVsDOp0H/5SdmcF1p8rXZey+rU0D6vjlWr5yyCMM2QkWjRaWE9ApvAE3DzjBOj2/Ui/zfoiLAtA7vNL6F6xya3Opne7BWZi0MPOHvoFTwoCHHZ1SQtCMn+FzCVvKuZZ09SHJjTdHhg5SLiC5r6ArSpEyb3PnDieIGv/pdDw7UQG8rKAe6i9eERUd5GAsmuSk7ikzL/bZeWwQZ3sT5WzN6quX6TRG+UtKOiCuhhNx8nTthXbO2Z8HEAoPBnH2jfZYHg99WXTcozOTStnKIMzKILltR70UESOykaDZI+Ddvue/bzrbk1IBRkWU9Vg7ksJoqWWFmzmy2DLav9Ra6j3ay4YDwGUh0Datk96olvteLijjBNrYGFUFWrkr9Vrk=
  SMTP_USER: AgCd765FnEwf+6IHkhZ0muTED7/3Uf/ZLsQ26fEc3OEPtI52VDXYxADjPZOY/Wl8inH5KtX+yLWQ5EhyKu6gLXk6lBGY3/BqkYQ9GeGFPszKXL382+3lSaITUbw/r1aQjujIy8f6oqeaFAKMMiCcYwVDsng+9uQ3XQCSfzgj5W/dgOChHwP+9IuFtrQ+xxdC1Is3+ptcHxupwRwtZqTbckDBsSjBMecCzdlKF6MyQd40hbehe0l+pLXfpRQIp6KxDIiWRBzOCx+VBv9lhpF3sH7cXqAseQPLCtDyTGmV61qEzEnIcBYcyobOrdNuGSVosC5WRSfOTYFS21TW9GhFdMF0kLh7Vv7ZioOK0fJGSnOi8l4Xqzbm0bNDsNWgfzbNsrRIJmuEzKqKXStvUeOSL752BMYJSnUjzeY+68Tl88DgEOiCy5gsLA0rcJy6Z511zu6ZgPLYBhttlPw/NrBaxOHgO6iyJFXTwkkrqj58kw0UbulxnpZfNkNmrSiqSbCw4oIg71BDQOFjUhRhv3DEeJWHlJqLTYJnuy7JvvccbYmyXwHg7JVa1VpVPLlDGMA47N08nSnTbSKQ3D3EjdSBK1PcjyM2Xwj2g6Jo4hrpR70KvrXBVvqT986khF1VWioRKbeoCmgcM6ds6QSIIdF2f+e900TN0Wasn57WirJOZnC3BRLi7no/aYa8DtOE+RoDA5QiFp85reAGrIUaLno1z20D0D3LbAmqlqY=
