replicaCount: 2

image:
  repository: kubectlandchill/sales-notification-service
  tag: "v1.0.2"
  pullPolicy: IfNotPresent

containerPort: 3000

rabbitmq:
  host: rabbitmq
  port: 5672

secretName: notification-secret

serviceAccount:
  create: true
  name: ""


resources:
  limits:
    cpu: "200m"
    memory: "300Mi"
    ephemeral-storage: "500Mi"
  requests:
    cpu: "100m"
    memory: "150Mi"
    ephemeral-storage: "250Mi"