replicaCount: 3

image:
  repository: ghcr.io/kube-pod404/opslora-payment-service
  tag: "1.0.0"   
  pullPolicy: IfNotPresent

global:
  host: opslora.com

secretName: payment-secret

config:
  INVOICE_SERVICE_URL: "http://opslora-invoice:3000"

serviceAccount:
  create: true
  name: ""

pod:
  automountServiceAccountToken: false

route:
  hostnames:
    - opslora.com
  path:
    type: PathPrefix
    value: /api/v1/payments
  backend:
    name: ""
    port: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

affinity:
  enabled: true
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname


resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral-storage: "500Mi"

probes:
  startup:
    enabled: false
    path: /api/v1/payments/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readiness:
    enabled: true
    path: /api/v1/payments/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    enabled: true
    path: /api/v1/payments/health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: AgCb97l3MFPdteHzlcOQqlrSo99mOZQmp/1ybtX2Xpk65FNVcuRDOJpaqHQ56un4w7u0efZLfm2DtgOU0Vv4vbyd5ITnJbiZlMT84j/cuLxRUr5dcThdF9fn/7TXqenODfS6gE9VCoiwnm08pxGfy8ebr4GQBb/szqrzKBtzPQ+xFHUEtsVqkWYhqfnKXwrAozbIljr5dAb9waQOsoVEfkjxIcUVOMGW6O6hkCkiQbYMBYfXPIzmUtHDPFv+lGm8axFc70FjBPgVE3tT5eKzLt9mw2lOqyhhHbp8Hp76lUdEtoi75CVmmbIZkVJCtg3389bjxgiQC7ft6Hf9XjfKi0E80H1MwrXyRKPgQt/P6/aE9PotttAu+7PKdzPmTYxYEhCyKZwkwP7SQP1F8YOrsitpyx32/P/iqJnmlwXfo7k16Xjqs1LxxqvIc/0ZleuuUdFx1xu/ejFFnP9R0ditnB67mgin2gGY0VHmeuPrZO5L9Nb4KJ/mie1T8L8eXcNPja5ta11giF/sAQITtIhrfk4uEe3leoPS5MAY4dmAs7ubYRvUCaBuaZcPTPonqciFzyEg4EV7sRkAshl0EsViziGgNaPz6r1Nds7Uv0X4bhtwymgXoPl5R+rWSXWPUa17Fm05n7cebQz4ye774EyDnMDDEOA5nv3U73QH6TOhExsendE3zMHoesErMYC8ImOQcbv8miI=
  API_URL: AgDj2WwAgpJInunsnnLERCiD/rnmO1Ku/oogcrqnLe6rT13FuQBXXH8A0N1VYrZZ1ON+6aD/6EREldZDZ1RFc0PipyoFf2Cd29qRfAvNWvTII6wCG++Bsici2344sQRkGk0xPnB2tscHhq4Zjn7Uk/D6iQrvxOtWZYHx+AXCW9917RB1cfvkhmTf/GT1/29HJAYEcMnOzp3uVM/nB20MUmGtkMsN/w7/VH9w4tnmFKX+nvQKVVOa3CzSFmKmSANSQ239ffgiPvFOpAqgQnydClc3/eVkVO/FkdmX8g8ZLunjYlrDUKaCuE1bQ8rfjx/vaNpYRoDwO6xoN+jaK8zX6soC4XlVA6niyamjs20x6C1OvYS+pBf2QaHLYDqPzuMq5dk4sa+WzdjIT53FrJUkCLQxgNLpMM9Bsw+z5WBLNPlaMxbIkTulPdrWmS5xifkxsRbJiGKvjLCLf7TiZVeu+K+RRcS28iWA38jX3fR7TA89tRwKqkwSdlk3jAza7xWYI79+/jqKbPUV1NO34j2vOAmTC+HY4zzn6GtyhjwJSr+jR9KFQbqi8zVhTOzYn4kjja4yy++OornvBX4RdyKkhQL6dzQu7OLuo7sHOVTm3yx22eWct9WAroy78IYyQ38ZVKRDDl2tWe0u4tO9LHthKjus3HoDOcYcsvTv7Vagi3kzUxKwe5soLWmiCkAk1xEjx8orKv+92iIF
  DATABASE_URL: AgDQB2ssim56o3orb18yMUGtCCS2FIoaPlbg8a8tpOX7ffR1po0oTXD0k3fiADGS0rHYhr+LdYJB+t4Bll/QArRgezHBfhh/v+6KtSOgMwBLa1FL2QWEX0G68JLlbBpBkWh5dT2QFRci3BWbbqJvI4TqznXpnWEloUwW+BNimsFEkWBBDTZcaIpqTwvvudWgPWiagSGVtXCExt61U4Rcm8W4dQzuVenMKfCJ5g+7ZOHYzpJ3DkJvgQGCF9iuHuGzXBEc6GUiNW1m9Utm4f9SFQTW6Z8NSY9FTuBWngfXoP7T+cp5H4RYAW59/QNRHHy4o+DAC7CUXSehDWLX36i1fH5dPfau5ByS2def0TEFvJNK6RdLW/W90iccNUKNSKbD3hwUVx5dYTbkQK5jXLsylqnLLGNKQbinq/SL5pdYEtDucc78l6IpnxLwhRf+4jugnQBcE1872kAjvq0aeF8hd5D18Lh0Oytg6gErXdbYQqdrbFfC63nWq2Act5ngRYkONUS3nHhCS+WW6BVHCfThTzRICmuU+ASslodYrh4qW191EmcPf7tDw0GWpi9TPECXqfQOxs44YIH/po3eTgSoUQRIiL4YYsF0NiE56GHiF70YEl3oCWXBbF6tku8HCtFhxypLtg5/fNzcs+O2QBrZCXT68fDaEYLonjunAAJMjDsGch24jyM9nVAgnDjVsFF115LBM2DLtC2WzEg/AwQJiwJ/QDpLpnq6Kk4efzlsiqVruHqotj3QaZsB6ykdzWF1fzUy3xcZkJwhvrM/HyS4UAbZ0hipjg==
  ENVIRONMENT: AgB65L41Xl8/EGmjuhQWwpf5tV+tvumFlMtt7ahqKNgQRlodiB5QYU2N5kmu3IFfWCEIsGh/LmPtHzRYZDfXE6Npjjo/T/EGNN7AKzx1UDzNxASGmDKfJS9jSv1MYsWdxVrfFbD7n66a6ug958ctYSrQwHrQrqMXs8OQVlutF/34F8uqWm9vmR1j0nn63EP/0bUSkKLPfjSoZGA6+GoS218G+gvO04BS7gw1Va2qJ/VbrkMtae2GZJDJAKbD+FHwMBYc5Tbm4t9J/iDduFuvf0mLE+ST7gOrGrk3ZHaOuS9xDgxbmu6pM4VSCnGrt3DJ8hZFCiCosYHXNK6uBmGrlimwtj4PiECKm3EkQKG7z8Ey5XJrrfpP+OFtvNcSqH5oD4Xr2zbmDuZIsCghSFm3JTnA3iw60b4FShDcp5D0DbVmbMEPjB29iSDG+gdpuT467aLe+hYzXPTMD9wuDvpTy941sXeD1K8ce0Ap5EXRkUYruKm8j49mjkxpQOfmOAWO9qTH0L6wjc6JwnwK1UbPThcBTQiBsktKHTDdjM7S/zlzCP+ODYsv5HzkUyQB07eJ4h8DtqAkMS3yf8tJ97eemuNgkiYLVoIRtaEWarvZSK0w5/yk9gL13SLZ6AXA+FEiiKHRvG48r9/h6+LU4kJ0m2E6p+fBxhrOKLZMUoOFNCFloYN+CjGWvx+JICLHxTcW6w4fAVlyavm2UqYV
  JWT_SECRET_KEY: AgCSAGIOsnQU2wS8cRdrklR/XTm17ntpHSzopAJ/KKnduVOaaxWNv5oLXDjDOQbNdFBbjiSBbHERoOme1HabapXW7JP1RV+fl9MdQ1G38+jW7jXV62FGjrXusTt7/IjGJfZZwGPw9/LaxySsEfkszwK8BflpkFG9y6luUr/fCRLwWtdTt3+X2Ewts+Z7op7IPPvedqh12+ykXEsbTNEWgO/P7ehPVftRFm59OKuvKiKqkh42+msPUhvPNKDqkcpPn7QZjXIE2rFhlFlU0F+NBcYXJ5DJnrJn0sGFWV++EycHtF2VaFwBLgIAJYIlAxRb/ncEj/cpybDDlcuJH/k4xNxZ9OQ3be5oAMDF8WqCPKoyvOu4i6uNG+m74NjNnQZ39Tg7Vq4b0E078Uoxdb7wf3VHRFArw3vtlpsgLTGaulEBFSJC37DNRV5Dc/MAiMuqWIW//bc0Mu80ofvMQW+bQnnamQ5WDkqTDqhI9r14CaC2iprGK5kvFM+/NbdaW++EfOfUGTSN53cn9au0xBrG0MqOLJaUye65MMlHqOvhYJsKpUwMNyAIL2O0gyZ0gppCApkH0ZYq8eDVUpITd45OkPqUnNpUWUe5SZdWWfR3R2eDOvrqYMjYcXQyviL/WQmDBnNqQK8/nME9PNeRKQXYyPGCrb/V31OdyyGcwg0+PypGjbLVzPex72X7Ru1HwSTqFYsQYwawAaDTZNpaxy87rwHgTst3vsjx/Znbp+eVXaBo1w4TYLQ0VxueDU8Bb7eey3moim6jy9c6OIAnTZ6UKRLFmWC6qQGYmTD7KdjXFnRzkIrDDgqRU1Ni0Mn9qGNTgW5ywRpia1L5k/GOINXF8Y9ZPfi4zrCMGyL8dPA7soyqkBV0wyUvdY9iFqZ00U9OWMjBXqHS+LFLx6yMD4oubKMPl1EZ/nA97ydlr5ac64xHx6gaYMFwIrtzj3JcN1zomDunOURbwYlhn5qTdgXgz5vb9d/poZXU0bwXKGREYC0e4b/aJvL+zGqD7/grl0fIWNRUBn3BaB3GokP3jPmWEFasPymMWo9qDtN9OgIxFwCYwL6O+/rOv26KBm6iGOoHTpWoZ8wfA5m1hewvha/nOvAX5Jx7eRW+7tVYFHwxqWWqjqMn9gx7IL3j3yA9hyrHA9murKOxVv0=
  RABBITMQ_URL: AgB6xCycZVMFDb2H8cdckKzg+qKu8mK6zGQdcTkJTigKfmzT9mOCnbAyUe6HGQSEji2BTSf/yjuXm8yPxhGG1id6hWOTpLG+CIt54garsY1BsOzjL6as4T/rcca/7Iv3dtyy2kBC111z+8kXZ1wVrh8CcMb4ITquLHyd/03Hy37VJ2X29FSqRD42VB+QeOboqyuLPKZViikKgW5n+lzt1tHORerOAbm0MD2dK+jYNvrLidreJ4BinWOdKECw65Ezl16k4q7qSLfDEJsFh5WcVmWavmYZz5uD0aguefZT/yXQuKgy6wayfNHGTeBDFRWd5EdfqQuoog+NhN563kCdXxaQSkEQWHyUjAv1YORAarZfMpYnmYjjzgSBkdVoiLSgTkyfT3S+k2uwcTNxLv0LXCc5RFFizotm5E6ycCu/BHVhT3+8ZgU8OBLBdpv6hrCdQ7TA+tvpRdRFg1GcaxGZama5b7ypBG1FGlpW/BrkaMVuCEW9mVlKPY5sfgCV71ZxtAjiq34K8r/XII2oIuU7intjEzagmzDU0C9u5UpFANwCS2iVHPaz3nuTIJWGs9xKbjtCye9/Mg+GFJjPDgLhsNeCR3StHmkJnLxhGA0hCRinM3P5BKCJ7wC3UdLVRBJg1Lvi5lTCxYvHDQh23KNoxT6uiF2J4FWZ9TMrEbOKuazteKc/WrK3so516zW1YitnkXmEwrSUI+W48umweSOBPG/ZOk+TlgN0fst0fly4TzDIRkY0b5Qc2FX/U0icEk7Nsyj4
