replicaCount: 2

image:
  repository: kubectlandchill/opslora-payment-service-test
  tag: "732c021"   
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  port: 3000

gateway:
  name: opslora-gateway
  namespace: opslora-gateway-ns
  host: test-argo.opslora.com

secretName: payments-secret

config:
  INVOICE_SERVICE_URL: "http://opslora-invoice:3000"

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80


resources:
  limits:
    cpu: "200m"
    memory: "300Mi"
    ephemeral-storage: "500Mi"
  requests:
    cpu: "100m"
    memory: "150Mi"
    ephemeral-storage: "250Mi"