apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}

spec:
  encryptedData:
    RABBITMQ_URL: <ENCRYPTED>
    API_URL: <ENCRYPTED>

  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque