kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: admin

    additionalDataSources:
      - name: Loki
        type: loki
        url:  http://loki-read.monitoring.svc.cluster.local:3100

    service:
      type: ClusterIP

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    enabled: true

httpRoute:
  enabled: true
  name: prometheus-grafana-route

  gateway:
    name: opslora-gateway
    namespace: opslora-gateway-ns

  hostname: test-grafana.opslora.com

  path:
    type: PathPrefix
    value: /

  urlRewrite:
    enabled: false
    replacePrefixMatch: /

  backend:
    name: prometheus-stack-grafana
    port: 80