replicaCount: 3

image:
  repository: ghcr.io/kube-pod404/opslora-customer-service
  tag: "a1857c1"
  pullPolicy: IfNotPresent

global:
  host: opslora.com

route:
  hostnames:
    - opslora.com
  path:
    type: PathPrefix
    value: /api/v1/customers
  backend:
    name: ""
    port: 3000


secretName: customer-secret

serviceAccount:
  create: true
  name: ""

pod:
  automountServiceAccountToken: false

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

affinity:
  enabled: true
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral-storage: "500Mi"

probes:
  startup:
    enabled: false
    path: /api/v1/customers/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readiness:
    enabled: true
    path: /api/v1/customers/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    enabled: true
    path: /api/v1/customers/health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: "AgBrFiFy+hyAsT0acsiAciheX/Jg0mSY5ym1ZPKvVN6AmCli4TVoKmFqjUXIHucvl9V0GKcBaon59NcUf36wNc2AlRUNlKip8cOboCYhFQnd1mW2sxbR+NOQU9xNzdjTnK/UhOpyZghZy+2JREdWwyn87MYqtl8nmi0saFBXsfiVu0cAoQt5VP22MLljRk7vTWVRwP+Ymwb7JlATdGEdpT8e8O2nPcSi1kbVL4OcPfLcjawf1eBmFhpyQXCgt3AZ0iDxDIWfy0gqH7mcsMjP9VuDaHETIDJF1afv247sIUMI3mPKvxJoTbiToOOXzvZ5IOYWpNO2vktLdYPzlcdOzIEXQbVuZ2YVqLYvBgZ+9HaBjcNgsMALG472cxQZQHtZSgBiKcFtir45oqvWEowaDKuWb5MsUokgpuZWQWAKHJgSYo9mHDNnGUcecY8jSD6Rkgr9GRVV5MtLHffNNcPH5c1RlrcWvf6/mlKtZ4+geKkySd5oqfW8/gdWHag2wiMBO5gdergHujmjiBlAitik1PL6NyEWsVt7KvgEqBpArHDJXbxSPAbLkgkTcDZaPs4Luj4WtYwofvrIGh490cEFrctH1vIDyi/1nJ7DUH3hG6Fci7sJJRfCarLTcA8cp0IHWZ6L5PXKK3z4fP+CE4TduoLOv6pJXochwYT8/kDf8k0WrBXerzoewq3HRMdKxdvfLNW4WKI="
  API_URL: "AgCcB+R154cfdhcrMPcliFG1qGVfm96cIGygkDxl2bvYTKwEzQDo/Yc8wZEJF+mRw9fMXb+/G1oWJnQZf3VyXnUf7YGe2kDs9y0IeKuOIfHMnTcIbx7jxNJqVoxVHTU1S4vA1phm97rfay41UN9mojdPMFbu5PpVlCDTeWgj9sjq5L3JyleuRxkLdOR+UxD9jp+bBNB9vaCN2RQfdN4DSRBkkG7ybfCAwOeLYFgVa9iBWRswKNbQL9qqnusXvpp9GodLbClG+G7Mvtpn/m1rD/ck9muiTC/cU3Gqi+aQrg2RQzOkkFCdkCbG37mk1CuYEoczlx8fe4ABtkIyT0ppPJJN5TUH3sO9W4cFSf2ZMMnvlg7UV0Cids6fGkITitUUjEllmZd7ljBLQYGrTNqWK7X9GgZsJXscEZadqAUoo15/JBUcej5jbTfmpmUGd1+feFmSma6BcMRpOk8h1wnJ2Lp/YwpGlepdjqgK5SgdmrGsawJn5OCu779xop5xMfNFUoyew9k/02VPL61PO5oRhGdZXB4z6ZH8cxN+ChssgVZbBe0BBnUkX9X8cPrDrLU2cgJLn7wkKLT3jZnOTIWkQLlKQ8WTVJFmEgH7fD3TvgpCekNGJv2fkswWwxKN4LnWInpD9KOxa8x8ZZh3OBMuJAtgc7J6KQj4XrSM/0p0QCqP8LW9WolbyyZ4AcPF7nJhGn37EP71BTbj"
  DATABASE_URL: "AgB9InP4xc3VoCKHLJUX6HNbT+cUTUizgZu36gTSHlZeJzrf0U+RsLJT+k7TuLk2xxHkaFOfy8bratwoG/LQNS9h27aZp688RGx6EeZkKKx6wIFWZ3aXCXPHQWFK48jJ0uDazk5anAOLQ3GIscB5OAWVpilntT9YnPDUDZm9zQZbnQ28oOzok9k1vQyrV4FyznfkRHvGxTvGIZV7Yu9bmOhMV8aOesp/WYw2mE3oGvDCSYWiBqlAHYWY6QDfwlpeauesXohNYOXAVsHZLP3qv8S+HOku6n1MnJOdI9h9pZsCilV1A8dP6lk5hB7gTGkskN3KekpyMpKQXMfFYo4ow9jaQQRDQrIuTSyXt5AmjEQ2t0Fp+7/Xx6FMr67vgm5MFPlXa9xrF5Es3xTRt/U3bqktPotwUP389YZt1/1KZTF2JmFG1BvG3Q1K/mH+T29s1FpqYc67/LCc9H7mRBxPHwRPqregkgXu6fwjsnxaRiNw6yH5YHDJNh4B+dB/2CQ42hP9V5olC1IvjzzWV8eOM1PcDwxkm/dH32sFk+EQfWGwkd1Cf+QDaM/Lchf43ZtDlzC2wQIBaX0WJmrjPU4DvJMJl6wd4WpzZh4H9FCHfz0RE0NX+oO9AlekZeeKCNQ5XOJELQuoBVdqZloJcka1Sco8gH3MCvhB6r1eld9MaRgzYJVpnW/oMDj4EEKKa9DmuUUHBo/649JkvDkanqVSy1oSyGl0xdfLdllc2vXgjafpcPILXKPIr0CkK4Go42LF1+yoN5hfqx/XOY7NhqavBTUFWHaEzQ=="
  ENVIRONMENT: "AgB56E9JxhYAcmhqSoO40eGDbkHSrzKX1HDKbuyipFvqqhcaSJTCHXS02jr3BH+jjmqmrouyfEUNDvDASqPJLB811OoJ6fTvepDltgPU+MnUa1psVYakSRNT/eCwlkNy9yqUq2tQGziJpzD57nR+Liq75VBkU/U70lu2E5tYOQcNqhaQ+U27QWYZcjksxsJ/0x9wIRV6LwOy2TbscJY8KgLUqjpk15WUxt8JuHiA8rMfgDK/mXRn+98xIDGBR18TA49lYYf2e8uU/Jegn/qY3QBNxnVP8fBoFAAQf/RUV4qSmAr0CrFh40fDk5rpBUaOsVhl9eRTb8W8s/Rp8ILRjPzY7ineE2tvE+F/kMbCxSQ1SjUojd2yzjtEh+L5XoLpnU/PXw24cb8/mPrlDf5gpnJ5HQ0OkGAXhkPQQHIYyGjeiQcAp/e9xGEraXrbUZ/u5urH2HiawHvo9wm7qS0ww34NUrcXByEpRS4Cg+liH7qpKtDFjP97vrBstQZtKF5MHmNsv+jjl8Lk7IQA9uoR/L2tPciKEZIKL9Ng3CkJxjzVBmBNQWelpyvSI8K0JQ47A1d2Uyj+cmR0fYObGrAWng6hEh58MHIPmtnj8toqhP93eVD06eN9HCItS67UuzCLWb0Ei9j4JqfFzODgyaBV6A3kxN1L76k51t0cJME2+DOH0pDHlVhSc51mQRMkktvAPZyy5iTU8/5Tju8i"
  JWT_SECRET_KEY: "AgB022V72wD6IlBHcvTnWL5D+hZegoj+T2pdsmDmqoo6qhQp0FWJ/67sEKRqJ8abMOMVaknyNJsT9K7jqv9W1N0+uv7Q8x2qEYhg9lhp+vosZ71xvwRsFbqaVZUIRMPgRbrfeXWm7UV+Lrwk6S0IX3qenHNxbE0pYaZ54760pFXebM8dQvpz5WQpDBUGjw4Zab+BluPNKxmD1bv6nY3xyEyvsa5Qgy+Fg5rni5hsHED5nHb5Uf5X5aOF5QKhocmRDUZgmdKIoyn+5FrZ5tN3xZqkBhnCrh+UWW4+XKr3+z2I3JeXJj05yBNDnWaD768NMe//oFuSlxB/YtAlFBpIxoOZbvTW2Zgsq0iR2KC9CIMO2FypsC9k3koWhYx35frsRfpHOIaET5b7obhEJwqWJWBgw+WmX9JmKLt+Cmz6gv8KGQZsjnlQOEVrsMxkpN4esrLUW/cLoPlhbQqlHqQ7eJ1MuZiMBIB5S2bP1XvhDIGCyQAkH4mUX7mtjkRtfY4pR1pYL/hbGBKb+VFZiKwLEDYo+W+WdnknCDgi/NaLSMNZtk6nBnhi2Ajs7uEvJJmsxR+0COQvxTYSGzMhSFR9qMD0uaDBda8W+sIf5/6lpfq1POk1K11hjwgNaT/qgEYDua6IVR6N60lLIbTgvWW+XHlF2qlKTovT0KzGnku1RPOJc4Ht7uyCrAdXdaFVXZ/RtuID8D9CbXtuLaljIc7otOCPQlQP8I/1upzNEHn7vn+F1xgnxyqxikad7cXCTpuBWZ0YY3WXQExym0U+DsTL5BVv95DAmXhser+6dHRRuywjMQZz1AMTgqdvcSV3h9UMuVoFw8NQdJncIIh4otn7fPfoCkoFpRR32Ju91jkKBX9ZZfwmwUaDjZ8rhYTg4D5/DIEP7BYtACpSqZDehUQiilkFoYOAHhoSy4y5fjNRzSDLVLp4BxMoOklgNTE+mabVMFkiFIjhfSZ3PuMq8MfRNm62zkcXZ8h2y80Ln4yCxoGVN1P1CLnOhsScU8qAdn/rzZKLTcUg0ZTPNSzhTztwPbDnGTdo9kV1325ajAVSLJTCba/ulGweg5YYgFePz/qoaeQYTlH/M6E8kNx+vUgEkxWHbibjVXBG29PaUjrK6rddGTYF0uFLMvJfw/TxJ+gPBaJfjEEBsSg="
  RABBITMQ_URL: "AgBHDmYfSmZXqcwU5ccZkc8qzi1JMe4YWdqkEDCGkXlJhJcymKRbYD/6XtZVV+yFkmzhAYZZOcJLf3jkfowyF2s04Ey3tlIF+utLnxd8ET4UUEGU/jcgOV564wApRTx0FwPjLWGqvt7OFnbd1OnWfVL6FM/2uwNN44QXZrLqD2a3jvaY9nYU9US7LnnCw73I2t25K2X/eZbnm4lYJ4s6eDyAWTWCEfEu191frPBXATQMsyFB1ZhEw/yNwjjPTZa3fEAufxjAHuDplhnPXkp7oURu63FZQuB0UBIPxMzt2uiqssuQG90fnxpSRh08sChsFpjdOtakNWcoeY6oooB+KtyfxCl4uMNNwd40wMuj7gneSqCP1IDgdSmKAFQ3DXK7crIUjm+Jjjy9qxwBxnkRIW3Jo54cJpuP4uePT/iEsHNIu3acl60s4SLo3VxVBEB/Nd716V0qry0FiHV/rMgtc2KM3dPt59R5eWt3xSXilbTpBaFSPU3hKORpQFVy269tZ/EysLOxTuC+qOM86p4CLwaePXeKjSD9s+nLBP5ePPUW0KTVji9Gz5nBjkSM11lLAugutGGqgGHPaq6ovN3YwjDMPbh2DvOf9Py4sb38EZBYGeAQ+GuB0ywx2DrWBnY7qKj7cndjiZSHVngeowRGmHh14Zbp9Ug8n2p/Kvmuy4qy3AEoUUlhUSqybbcHyaYayJk/GBqUNYqiuf3aBsONGAu+Qa9BJDo7JB8tvxQTQZTgUYaoNo45xO4YnGugAnU5Ag1g"

serviceName: "customer-service"