apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KUBE-POD404/opslora-helm-charts.git
    targetRevision: main
    path: opslora-helm/apps/auth
    helm:
      releaseName: auth-service-test
      valueFiles:
        - values.yaml
        - values-prod.yaml
    
  destination:
    server: https://kubernetes.default.svc
    namespace: opslora-app-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true