replicaCount: 2

image:
  repository: kubectlandchill/sales-order-service
  tag: v1.2.2
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  port: 3000

gateway:
  name: opslora-gateway
  namespace: opslora-gateway-ns
  host: test-argo.opslora.com

secretName: order-secret

resources:
  limits:
    cpu: "200m"
    memory: "300Mi"
    ephemeral-storage: "500Mi"
  requests:
    cpu: "100m"
    memory: "150Mi"
    ephemeral-storage: "250Mi"


