replicaCount: 3

image:
  repository: ghcr.io/kube-pod404/opslora-order-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

global:
  host: opslora.com

secretName: order-secret

config:
  CUSTOMER_SERVICE_URL: "http://opslora-customer:3000"

serviceAccount:
  create: true
  name: ""

pod:
  automountServiceAccountToken: false

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

route:
  hostnames:
    - opslora.com
  path:
    type: PathPrefix
    value: /api/v1/orders
  backend:
    name: ""
    port: 3000

affinity:
  enabled: true
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral-storage: "500Mi"

probes:
  startup:
    enabled: false
    path: /api/v1/orders/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readiness:
    enabled: true
    path: /api/v1/orders/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    enabled: true
    path: /api/v1/orders/health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: AgCLh0RR8Cgnt4i/IKJ4lmaMyDwdkAbIBWH2yvjRbDD8e70xin9BzjBAYbvTS+Pn8rbb6JCqf6abH8Dp+nr4hCwQhAFCWDX1AmsrFTo9BVd4R3vir9MbatJ5npywn9ehF7gBjX0sIWfxY+o5xFleRXEsWJA7fVoGdvyLr5p4+9k+xiz+CgpLcShcuTlB3hF8cXrQd0atTY+vWZrC8WMbbqNA2HreiosrWOERntE7NGgh0wpw8ZlXljypqi8QhZKMKlJZh6DFZeXJo8sxY4tgY7KTc5xfj6+Vrqh9jIEy9P/LAzdK/AUNeEe6+hJNAv+tM7reNj9wgOoWjm5dKDz+E7UFBBGg10GtzoQE6++RAlBg7KDPS15kR8BNqGA9wfOQ5ZbikPFaGOjoaZnEsQqwZgn1aQbY2AEYJRGqUQ5Jz1Aok+cUcYHMAyu9x23L4bInIKRfuPejfx64duiy8fy6blj4nY2duo1kOyMoZrT29MJQhTVONuZD3WogWd4zrmxeAdWzVApV1kn6K50kDFNgo4VwDW9nLwcR198SawkK3SlhUMWKJ66E4oo8RSAx8U5awl4yMu6FzS63n/gTMrSA1JE1WhdLzaT8xI1eiwAkl4OWkRrR6LBSQZvRz4tElRP8daIG7lbVySTlFDCLDKds/lzHWgzDLJr0WkLypEJtyEIzijPBMQHbyCELzu1IacaktHZbN0k=
  API_URL: AgCoI9OELBtIoLl4kB2K2cyBsN4T8BeaSgKvi+1jH0yOGBwEct4MKgC6d4H1VgWBVIyEULYSKQ5THuLBsVW0RKOO5U45MN4lp9W4emMD+4cOdLcE+NDEeTJiALFqTcEdCN0Fl7MPaPF5WNLtx3Jf0QPolnlhk+2xMpIeevZjfb31vJwtiSPfPb2yKYXW56Ixzxzc/WtyBLoekHIS8KEdNvfoLgi1pX/rhXK8BrrpUmzwTjIbPQ8kZ2ruPavphn9dFHKvuhZCYy2s73MTCyEqNt8nR96BxM+GJyHyrAVD13jsqX/eucTeBO6IEV9/bZGIJsCfRK0IJ4WoMosYYMfV/LbFuoUeMhZmN+w7Ud7yf2u6j33NDaPnMoFwPLjfTdkVDKlqx/WuSMJB3Gj2E2QjRkBcXg7w7ybOubukCN/dTe/v7xvwC8rBXAPr/Ho5bymsV+irIupCJV56LvkWpoWWZa57nzRHll1WXKnJrqcoeEEHf4f8TtFECEuNzpEgVp66++kBtqwH/cMjVyF51sOguZu3drae0na51hd1Yg9UaqfXmhaNlhBYUkUcHjbNZoNp/7rhfijkTFVRGGroAc1cbUFHBTx+v0Fv+D1QSvFGkZw/hH6mY5tAI8F6Jk7NR52lcF9bPked87Fky4k8gjZv9ct6tihcYGVqkt2BvuQZohaBTw+H7dk3OI0ioNkG85ff5E73tfYC1Uz8
  DATABASE_URL: AgBHU4wyUlklhs/wD9snDcKFB1kVlfZE0wTEkCoS4YoP2YmFdE/JBX5OmWvoKs/hmeElrDbA9w/iehIA/EscRqXy4ks1Z0XCB3WhVJjPit7xNJOQe7XreLLe+00b0mzykRwkj9+tC1yt/gHKEqHSZn7o1I9QjzqkwG9MSGit0+H+rcom9OG2iZXdFQj/wfA8p86S3ncsD+DLmgJeG4/ehaL2uclV3zJg/Zd8WjXh3qQSP7nBVqtXcfDpE+F5/sEit1+2A78o4sS9hIIiK5EnmlJgOvRnh6qCahw0XCMEmnAnYQSXysXiwBkH27XB0Fa9D5wo0gi2OIF97bQHuN2p/h6j7qkViCoAc0/zLIykDUTcRlZoWJ/6zBMbYVpfms+NBPmoUBVDFaDbkYKps7/Y6AcDhnLqhwJ/UV+AEaeqYGi503BK0maLxLRvu/vePqCknGmzBnq2SP2Ga4Jhh0p9zHw+X7X4TmdbgUCnj5IRZa+WwPkM83a/4GLTg8quX7AeQzuzQXotVCGqfery0TvJYREJXewZhe8aTHO6zhDQO/tTpOUu3xltLig/d1FnAnM5FoULAmarhXr77MTdIjvWpjtKdmnWLXbUg0Q4JVK7lhNP1ujRyokpgbzRCaRRQfzimtiROiW5FKO6bwrxBlqE6Lbr8PLZOM1tRiD//ci4wlL11zLg9n9+ks+pqmDh+CnrnlBKqf0sWjzP7n0ksQXGByFourY3YL7wMC/vBAJ8mZbIUqmB9cMLpE0IOnHqcPHCXHqVYmBwN4NnCoDm1CXbI+nUyUsCyg==
  ENVIRONMENT: AgBnTI+aBMKW8VeqKbibEQS7nPM8jRDDh6q2/phGCPSQZVP/8NoVPXC9JTceiHHziXgWL+tE71JddtYMI/rDBEZJmJYh5fQlu7tr6c8CXMrexwNCV5Q8RrHFdHAQ5WT8GgajPCMwGDSXYQxoJ/POc5gB7txpX0c/2hs3bQfiFiYUqY4v0SEMQyMgnlMgBCnNGm/VYMWEn5WMzq9RNmE3O27dMJXz1C1KD7Vxhkre+wHZMTVkxSkF1GD6aSOajTf+dxhtZ21Z0+C8WiADk/bEdvowGv3Koxz25gwqM63l6fke3sK5FjgtFH8Bu5h7zsjPS/2xzJ0bXxTqiakg4a6KiIYnazOWAonkVB+GtIKSUVyzddH1fdMpxom5VEeX7LdvueOqHWG1eiUD9TJQCOrNkHBPHx7weYRVQw+PHthVZlcr0iPZZS7UET4SP7W4nSpS93ekhr2nRWOKOzh8+mhcMekCuVPfPRFlXzaFmRPqPYaF/BL1S7KwFhT14GOPq+/FElVI9xMbov+V7a8ni76zzz26QxEFvYG+JmR3UdjYon7jwfPQWpO1U2ulpWvJDGcDP3QgszTRPp8An8JEbqme/I2WppmzqlOOAAOsAeCc27fxnwsZn9Rjc9uaRIGjUiDAEmoodBNuxP8M/3nqLH7+vLGxEdSPp3kWUIZWYihFWM4rJBCq4WPKlxOm8OXrhB0mG3F5GeVwG5yPDxAL
  JWT_SECRET_KEY: AgDhZ/ZdYcTHQ/KbhgBzUS+haETP1b5+G+p92dTczmbXm5JZTXFdT/FyGpfqrfu8KgKq2gDORMK3/HKrme6xA+eDWJk4l5r+P9f/aKzgEGYBw6YZ82fozoVjYGk9d2KTji6F37h8ckhYrFV2h9z23PZJgAJ4ZhZW6b9e5wUoFLJ5LE1b4T1AUMqhYvO0fK/0tRgCjbd+OIiCmmzFO0sEFjgtlmyPi3IcESQ1Rwkn8+jkyMn/fndP/fYAM76OzcJR5Cql6qWsXWM5HVEMVW5gpYuy5rVjObwcdv4pKpVnF9esAsuT2L/Bo9uO42j0vonyIeBQp4vBHYRGLBude5sLySANwZbUAMsz/IVSI57h+9YJ1eYJxXQNJsfS8DZ14eFOStGRPqH3Gfqu8MGGeP1fcPK/aYzZ01sJIDommhAOztnlOGuZXHyetpRGDEujtgR79x9+uQX4V5ETeLYXml0ofuMeFSkaLb+6SO9L+LI8dFAkkWY0YmrnQtexur69dAGoZBHQIVf1JGXFSd2n1keAMvkjeGr5PXKIJHSPXK4rzM5o7tZI71qH6NsqwZYVDa+EIZf4LIgfjhtJvrhZ2zStUiCg4/0R9lLHtj7iynx3kVCrJF30xa88OwxqTnPSl8uY2R+uk/swPr2LhSvWIm41LoBR65QGqKTCuMi+3lgKYvork3A0B22Pv3SeqwZOkn8szlkSk9N8+IDF0VUv0ZKs9tbNsrs4X1AfRHg6IDg9rexYDJqAFubBuOy7OFJy4tlPBfLBvUHU5G/pJlUfJ35lxTybAkh0kxaR/ap9zJVx9ZSTQ+SMQbf0vuCOCem6i5p8jnN8mbmXF/4ZiBvY1UP2mlpVScBRDKLuvRejPPIf/JKSfzMAHUaz79hkiCTJu3QXwykWM+FusroPU8uAOtd9hiaxJKgf8GUs7COkhixlomP9wCCIaIRUrl9hqC2Po33uZgXL5VARHQKZEolWorpsriLKsUpj9eIgTu7oLJKJO5gto7OGhppbgUYgEwKLXGFIvGEWPSgNa/EnC8IQbCm2z/6Tw5tuu+gEa47+zXpxAmlHHFJ0bgb0rWT+BF+qoSkDu/IVJoeYljWpHgruax5EY66b+QoqFDjszT+VxoMPMRX3AhKhsjKxKDLmHbXivfZLPD/C6ydLSEw=
  RABBITMQ_URL: AgBuw2g96iZvaXo8ZNbetkcw+Y/0GT9j3r4G/F1HPH4GUvTp4KduYAgnbYHk8BmzmmtVHoNIKrtkqRbQc9zBLfKTY0wJts25WnloCkMMfblM+JOSlqxJK5JlW+5+KnYrP5B6cLcPVz9teLqVyXHE6ZtJlJpJUKVCHjUrV30Eq4c1WtaWPpD0sLtHPO5tImLSlJeB0t9BuNV45JCcUMujKNGlrIrPC7Uyy6YVpLqTaVzlaJgBBa1uOqas6NZx2a7K8IRSxOzg+EkcgSiC4LQ8+qPKDQgJPAJC6nHOF8a2dY8DHxFd30DiSLYvm5YcFRoYnzBG2ZIvWlgIO8SF/ZU3PeurJTK9WLZL6oa/W7Kj2OkwYIhHDyfhzoyKapvEdNfNa/nlmzAsRbaPI4DUz1bwQGbr3Ttzg89GF86MpXTS4/8GiDdAtblNd6q6t3Xn3F8nQmpMmFrzJnoqkX/X1yLuK5JJDuy2rpiQsXuxaq4VZv5+t3knalJLR+CmJD91NcSM1ZIY04ENFLgG8YIG29uFZsi05rcHx19bFlNVXmA0YajbNewSi932Zjqj5+LyxsbGrTVZoRfI1KDiJfPuawTs40vmOU9PanSll7Z4OhrVGmivmYYsSlurmQ37+nn4H4Ay9n363Rykju4C0SFONR+Sx8c6c7FiTviy6o0ZbcRmxVjZNFSsZ4GlQZ9vK4hrYU6Yo4ciC+ctf67NUt1zEPWyHREMs+JX1KSci6koQH0fZP+7DcnTQzQF9wXWNan324AqdVD0
