replicaCount: 3

image:
  repository: kubectlandchill/opslora-auth-service-prod
  tag: "1.0.0"
  pullPolicy: IfNotPresent

global:
  host: opslora.com

secretName: auth-secret

serviceAccount:
  create: true
  name: ""

pod:
  automountServiceAccountToken: false

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

affinity:
  enabled: true
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral-storage: "500Mi"

probes:
  startup:
    enabled: false
    path: /api/v1/auth/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12

  readiness:
    enabled: true
    path: /api/v1/auth/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

  liveness:
    enabled: true
    path: /api/v1/auth/health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: "..."
  API_URL: "..."
  DATABASE_URL: "..."
  JWT_SECRET_KEY: "..."
  RABBITMQ_URL: "..."