fullname: auth-service-test

replicaCount: 1

image:
  tag: "7616957"

serviceAccount:
  name: auth-sa-test

gateway:
  name: main-gateway
  namespace: infra

route:
  hostnames:
    - test-opslora.opslora.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  startup:
    failureThreshold: 20  

  readiness:
    failureThreshold: 5

  liveness:
    failureThreshold: 5

strategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

pod:
  automountServiceAccountToken: true  

affinity:
  enabled: false