fullname: auth-service

replicaCount: 2

image:
  tag: "v1.0.0"

serviceAccount:
  name: auth-sa

route:
  hostnames:
    - opslora.com

resources:
  requests:
    cpu: 100m
    memory: 150Mi
    ephemeral-storage: 300Mi
  limits:
    cpu: 200m     
    memory: 300Mi
    ephemeral-storage: 500Mi

strategy:
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

probes:
  readiness:
    failureThreshold: 3

  liveness:
    failureThreshold: 3

pod:
  automountServiceAccountToken: false

affinity:
  enabled: true
  podAntiAffinity:
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname

secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: "AgBu4vpLvKBb/cHMtOgV1WPZTuAAXTVkN/dFltTm+kpVsIofoe4UtqvRlvGCar/Yffnlsuupxlg5BcDK+dcyLNsOsVA8er3yNsfGye66krVrWruG973UjZrchUgF+BARTbimdlTI4gwRDgVaL32DynWINv5oTfE/lZmk7CnNilUZuGh8wsmFHdmHIZW4bspOKLQ8UZu1vKD/kvJ40/BFLY+TK41QV4y9k415mT1THiriQAH5M0/8wEZxEzSpnUQp6XNX2QoudD/1QtoQv8ZhfR5bvPCdPwSVJHFCw7c3b5oS/njWToN3fm0dvEl6CAoL9w5pbFhA20IDpfeIBglaG3Va68g+6Fle+68TXZlEFtC0E3ZuwA34xtJmLUB0QLDmcANlrQMQ8iF+kV53ad0K2gAopb652MTLU8eGTlp7zLUcAJdIz7Z5pinqNbaMfId1yCs4tHQMahc7BSjSOiCPo7IquoKsHyl4lo3WB0HLgX0N6o1a8DpEdcNmScdIT7LYrxqjrJ6WhtAKhLJs7OWSLA/9khCXvTY4Hc4lkk+gZzVXC8cTJIhgUdcS610TBWUUe1mso2zGOjGyYeqo30rV2iRfRA4Ytv3DBM7+euxMAaNBTaw6zNfrR7KK4OSXRnjpzrqJfsfcFSB7FfVN9Xvs2mgyNI6okGVYdsbmB8cgBksTxwO7YPpgkBmDbkREJLgpHb1aH4I="
  API_URL: "AgC9h7p1x4Ni+4+5Qu6OX9p7UWyKCy2FdAN79VOt/bP7/IGRpALOZ4cnFBAXNSyZ2yuDjCFnd5gRrqetfrVaNjX9l3Ztg/bDUCY9dlU+f3yEiWoBndoB82T2na2uGqAmyo22RkgAFUYzgyDSfS2kYHywVqf7lBBSwnXH7X3Hwi/97GpVnn1kJixxESt0e5Y+T9UwXRww6m1ovaxmljQD1PQi424EVl2n5d0JGpYFKbXiTBvXIziY2LLozdVk2eBorPPGt8UyZtQLKgPaRYNPoztEPZk6Gm2kI8/DUifYzZCJuFxa9s3J3XYqnobPjrHvB2E8XFGgiulB3SszEYMuFWIAYN8tVxtH4ZX1ZH1AYU2lT4Xuj6n49M5Ujbq6F077jrqQhcQy4gTLALntGGIek+Hry/NSnI/Yh3GNyInlXF/Ps/5TQiet919SUHLvY09pK13I/csnHlNcg+D0yAQlvVs0whC9lYDN1//uNHUGDlCzjPPLD7ymSyxspiIU7YtCfYXCwJwGr1gq8+kJKg6gTaxO+Xw3QYtqs68RTUpyPDRV8pMQuA6plkInip8rVMsbSME/QHC5Q5wgGnwFjQnJQfhogVXut97ejunhFpX+zpXOItYNM9Z4bjvQoM+NBcQ6U/pgtB2Sl+5CF/EfqiQ7cyco7ArFYXP/eYHokT5zMhHT5Jl+fEDnpl8fSzxW7wpTjmTC0W6D18og"
  DATABASE_URL: "AgB7syjLyZPJyJeC7cd5Hk0orGrKFYfstVlKP3mznv5SUcu3m37VAsK45eKSemtBXK//pZ0Yl/4iNQBEwkadCkBOyEpvEM7Ea29Kn/q0wCtyc3lPm9SnsSAwu0aoa04UI/lRvA3eB0XWf+5OXpzrCq8ml76CIUuHNSe0kb0fQ6KSkdcS9x1sEsDI5iIZn+BKorvJrKQwy/NVNTdwUDeDgGMEJM80IIa9FN+8zt4M2DOlh01JcDX0ArUtbQG5qRZqkfpiuzsqIIgFBlK7EYqLgdbxINa0wT1FiQfQ8gDc6RIqMD60QsbsJI9D9IARCgopH1PxnoMo4+a+J6zMWcBxZKBb8PpSLLj5Vh5yzPt1M+gW3OupBoxD5QCVmtEdIdoUmNkVzydJ0EG+aFQlP6CQQqk8eRn4jQU5pcCvDMcqAUqAogtp9vz6hYZu/qpXWYrDPKMA4SocfUInrq6bx7IcK2IQ8cnEZRxN6nO43RD7rOID+67eT0k6FTPO4q3ImHrbvJwjYHu1Yd4nTa+9SWqFTfOai06uMzeQCQi7VBVT8kMIGNjxkO5eSrzysbC1yPcLjqTc38SMJkEWfJ+Q/UXxlkXMSdE3ulexI0z6HbY0qAS8IcVxWkS7FFTkCk5hKlhE6A+6tjW5K0Gl3XungvGp+0OlTaTgS5nyuPJgMFWz+3VcLieax7Q8ZURw3phaApCfPGLEEbZ1QSaY5tNTDGr1n8USfvwcU9/VAoVYc5TI/R+gWsiaJif06q/arGl1iG11Xx1UYwYjgzgPLmHf2xeuW2so0y7i"
  ENVIRONMENT: "AgCfd1IQhFHc41Cr5cZ+at2gyx+qdjHqpLLas6N0mMjsw2vYLc6h1h3E/llEt5l+xZUv76SClApJrp9+fGwE0xF2nML6Z8EoV9E6p1dCWNMcpaW/ourTTPTIIr3EdwzTokvnoUbceWd5Blr6a8sYlTySfPvcD5nVVQ+90IuRUpCssaHXNITKy/0dJY87+U9WsfFJ2QPB4FG+Xc4vzLsCgas4UT2uz0qUfUYmP3+Op3SY4G7gI5OH3/fm0P3Hlw+kwz2ifZxERobpN74zqDWeo0b0nRBMTJbLDI4fJBRJlxtCA+CQRxzD/cDFWTykJV99X7/vmGN/dEyTa4T4e5adzLmcwqaJAT6y0ue7QfCwG5o7MPVYY4Dh9hJHAViUEtlVxsg6mlIvNGlmzSzP9PtpXHfM7maCpmEQDU+GjjeRLeGzgoYn1q3DlRTUIl8CQnyJBUD73MtotEkYxXR3X+AEYN3Bkxt4kMW7mdO5OtjZgSyIRT8muAkoXNm6gedhjPRRBBZEX3l/hWcpigbs/HkdElriyth1yeMiNX8pqmPCItyhAEvG2Ilzs/yMGWBLe7fM0iGNKkczC19p4TENsCxrr9kjgwCeuEOJupS1BR2dzT8i8gINaNNrjyV5Pk4aVO9q8oXK+0Iqj8MMTuPa7OPae79uZQvCgmOANKBIL+EMN2/rB7W9s1EOdIFvP3AlC8y3DE2yoT1A3q+gzOKH"
  JWT_SECRET_KEY: "AgCPkjOpi2vDpSTcl0+VG7fyRNIS6fW2AtAtR7TCWEYyH+ioANpX58lh18jubViDb9VXWl9RupdcB4Mv5Y8yiUVs87lUAM+1AUz+2SrL+4YCpINMo2gyKY08ffu/Ot9ofOlDCrGVpLfbauIS2aJpq7nyxLaFEWg3/u/m0P1AdKHGliuKi1Y5EPK8cQxa7KpINDPdHm/qakUIWNrLr6i/gUggzkfdmiPtcZ7ZIvhUVnWYHVlyMnHXd0esxGsS28vpu4odvyNM5kYhKNom7rEDtJvcyZ25hP4TpIZSeHNU1/NYrP+wwH/l5gBxUK/ZO78WNvnyS1SBpK0bAnfCkbuB9v5Kwz4N1VqeVMvIv8SuB0pYGdTy/WZFSIIoJCD4iYuhFZLMVOFeBQCXCIxSFbkAfcIdqg4mKwwNAKJ15i5Ywp/aex24v02U3YQSQBLpWQTgWFMm+H3n05ePROSt8q9rxfL7Yhqm7j7TZUSm1rGgbT1JYpIomtYAjYerwlyQSeBn2XZ9ht+WOqVq6MsUYVQR517goiAybcQwWF3eck4PDUZ4aHKIuTUxYBer0Srhv8O7W77Qp/+y89EmepdqvHAYZKbTGXWviMrCiWs42VP6oh302lkSwHe3V8LORVzCEgkpkZmKGpCJYW2aKjNnmfhSDGohDYgqXrwsK4RnqpTMvFGtFvGPnSJ4ekZ5eM0NMlcuBkZSlwb2ray+ShpmT5jILatEWI1KdNtJmOqk0jszBi47wyTGqcUod1SJTCuIAH21FthRA4W/28/8QSGTjyZLH1/L3ZlHHTBF1bcjaMpxR7sEC3DxJRQx1hoD/uVynrxwINWqJ8XOLUW7rl/VyxyhmghKpkqaLl7mFtatNHeM+d55aBVG9NjBNXw8bmHIWPCpfftxEFAFXl+6ZB6wGgapuFeUP1NByKNTnFRb8dELBG9kMZmXTLfu3u+K96ZWfTTz++fswIRpVN4crXvGugk0Qheo7cyP9yt4hwohYnqNdxNIZMx+10KDizzO+9cEqZA3ye6ynznbuNUL9H+N8W9z8OrQCBzabX8XZtrIwwnmghYDrnNgkGMGam0vLDqr08ZoA3TJGplhGhvt8QYN3RuHoEgb1RHsPXStJWvSOpvNdpLat8fhoXJaTZWWCDM/LPUDs7VuvV+Xkdw="
  RABBITMQ_URL: "AgA31vLlT+5BBmhlUqWlofq27qqanWRysTNMVNFW9QosBhtNJ+Fxmf89BJz1hrLll3cL2sbdk33OU2/F8v61hVWZPQenH6IpMNaRhPwrgbwlDQbNSGd+SL3WQnzhxHO6o+ccL4KHf/21nn+Z4NZmyfvgoLjKYF4gVFNu0giD+B2WrdLZC2ztNk+tnbL+WK3uWyKtowzbgCD+V0RsvCY0QQtXRzomsO+AZA8fwtpmWa13g+vs9GlZBD5DEBaLoJJ14qzEBqzjnSoE76F4fxp6KTP9CiQ/VmAp3uEDAiC5fbXPv35TUpqTNBXcniKk46g2D6qp8u/dITpdYN3fO+ToZNlj5KC1af9PsarNyBnt/quX7jAtUYhORfVuWADMgx0ZF7t9c+fxcNbkSgnyYmwUUCnT0qOOEuw2fQjjGzQXISvSkLXA4swhgJIfLlRCA7Zbo0jZLFzdGFFx+h8pOr/lwBRL9i3kUgCG+Uzv8M9iQCGGccXi92NDJGkEdA4BW2Ub9LkaqfOJyJEYAoaB7yhRbT+UbGrcY/Vf5a7/9mCDDdmAxh4Lr+rZXIDrlAOOFu4ZlQI43JUTVbpokMsHLhm6t2i7WG3swuysRQeY2NBLM2uPAsh0SPxrI5aZayxyfL+mhze4a93LkUFiZ0cacjGFzSiYaTUSfNH6rM6mScaB3wRwlSnyqylLhaLMoQUakajICCiRzQmTQ30dGKZjmNCuFrZ+2uaY/OzcFdrB5xRQcc4oJR8IUgKhcU/4kAU4grE6xOk="
