replicaCount: 2

image:
  repository: kubectlandchill/opslora-auth-service-test
  tag: "2972740"   
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  port: 3000

gateway:
  name: opslora-gateway
  namespace: opslora-gateway-ns
  host: test-argo.opslora.com

secretName: auth-secret

secrets:
  DATABASE_URL: "Ag...."
  JWT_SECRET_KEY: "Ag...."
  ENVIRONMENT: "Ag...."
  ACCESS_TOKEN_EXPIRE_MINUTES: "Ag...."
  API_URL: "Ag...."
  RABBITMQ_URL: "Ag...."

serviceAccount:
  create: true
  name: ""


resources:
  limits:
    cpu: "200m"
    memory: "300Mi"
    ephemeral-storage: "500Mi"
  requests:
    cpu: "100m"
    memory: "150Mi"
    ephemeral-storage: "250Mi"