replicaCount: 3

image:
  repository: ghcr.io/kube-pod404/opslora-auth-service
  tag: "405ca40"
  pullPolicy: IfNotPresent

global:
  host: opslora.com

route:
  hostnames:
    - opslora.com
  path:
    type: PathPrefix
    value: /api/v1/auth
  backend:
    name: ""
    port: 3000

secretName: auth-secret

serviceAccount:
  create: true
  name: ""

pod:
  automountServiceAccountToken: false

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

affinity:
  enabled: true
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral-storage: "500Mi"

probes:
  startup:
    enabled: false
    path: /api/v1/auth/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12

  readiness:
    enabled: true
    path: /api/v1/auth/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

  liveness:
    enabled: true
    path: /api/v1/auth/health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: "AgCNXEiOjUvZI/+x5Rhj2AB/WO4Dvf4wLJGISYT0pNDNLJjDKGccedUddZOgkR5Jav/rffn38vYz3eYymyR1imkeR7wtYzs8uIZ3GdmA6bRvxqHQK0PwXPYcvJdnFm+SBumtyzfHMJ74Vj2bJuMJkQGDFAuzLQbfPUGXtaazDvpg8g+0rHrrlOeoMGqX8wvEUncqXRVc2TQtkNJZMeo2Qyid2cRfgN3zpUISSmoLvYiheWIsZ3N2MCLUFyqDWgfjytEkPz/CawQIqa1eBSnNtAwHO334fmGQ274uNAUY5fR99E3451ZGMilZfPAITnRtGmuyEJhSWhPCJuoBiQGFxdp+9rr7MhBh3bu1zbAETQ5i1z+inxyNenT9Tl7TP9XlZT82xAHSDqAqMC/QZ6SPED/7wfn6LqnW/1iqoDoB2elWtJc07wRAwC3f9M2fcAlWxnox7FCkcReUO2hkAYM+3t42GdtKhZuzwlUJWcMOyGuBTutrgWkGaJn3JdxgQgA0MbJxGSm1RJMXd/yAJithblIr1sH6PpdTMFhQUOg2E674gS66aAXRFHVtH2ni32NdL9qC71qyzIIDjzRsrlpQQX01RmiPQcCy1afwMVPTfDe1n1uO3o5nU/kyoAiFkC23nw7+xOBxabFMvf2iR1CUqv/2UpGYymwHWI+8T8wOk5pHJXJ62KGwGo5tizT2NY79JfAqr8E="
  API_URL: "AgBWHt8bK7bcHEijJpZ4DgeomCvXROE/4Qv0vLnaoVyW0gAMqAbuNrSmFeA9NNinowwLXKYs4Ww54S0GSsMBy90cDcs1hdiF1ZkTF9aG0clAbgueOrradzQWvs+LuMfIU+s/L/R6vlyW0DyIKjVNzYFXZtCX9ld7CwmW6xWkLzcgz3/o65anjt4/qCJ+ah7bnhHVHUReHqZgoKTpWeZzf1qJzW9jukg0xJiC1Xtu5nk45L10exAVGSYyolJzRZLu63xhPA9jrdPQH01fmOoLoUDKMJoE7563FK66TQ2ACrcpXNGa32V9Id6mtydZ4X4MgioYriz52J09sEG6C9QvkyCdiPnzke6AHbqmyUGpz0C7bThOx2SjYgIv6huO2oEgY6WdIwRs3FB4g2rASnD4s3XHDhlbypCyRajl7SOMNWGl9wg/p2YUAhrXNcWQ4aQR9BYezZ+dh0KacVD2yaE547IFp4O7fboqCWFqtABIvDFO9JBRBn4Qj5F4oZkASBEvyuPO4zVtQ6L4Hu3TIiEhI9BSFqOKCN2J126ntPk9BlP4Q3tSnpVU6CJ6EWpbNCL99uBVqwdWeMTyVa0+Kc8eE53Bu3SiHT5MM01vy0u0jl8FzcIm76hoT7cWkgu6uKaz8vh/T29ngdW6IVadl82726R4JXnXBXcNDvlKEttwh6hLwmJxnH1v4ciO0Q2fm53zaTVvsivuz2XR"  
  DATABASE_URL: "AgCk4KPRC3MycjrA4RoXkYSXc5po3vyUjwXq526yf0pudtBgdML0cRM4j6gLPhhKVfuPNjr5f4cZuKA8/Z3bj052+JUkuj2ZoqZFjph+YRiXFSuIM6MIszd+9Vhs9OBkAH+pKpbOkT9D6eP0+fQk1AXrFaGougmQU1xYjvbbRx/3GA8Qy0bDufnaR4ucKhc1XdhZsmR73S3sfDvUPY6xxevrbAz0OyoKfNreArOukcS1aG7cmBH0FseJTtfoTohooxuWioUOV7IQaM1ebSrYEGeRLHrK+2yqtvSr14g7G6Ic6XV3Wjbar5eR889neEwc3lXG2DF/42QVWPaAyDjBk84u7nCYy7zEI+wSzoklefD60FQuiS0g6gcvLt8SaMHNc/uGf6bSDDzlwewxR/84wdnrE7wyVSnyA3gOe/hZpczPkyYohB6LsgubG89iu2S++rMuyKfuMSzEh7UM6ULuphfNHpr8YifP2C9S7/4HPHx41+xC0LWkuu05kS+N1nP+ujb8WlGLGkxEHRTcSA5FeZqob70mkK5KoIkfx5O/4slUXLhD/HxpFQumxxQeMdmlGSVqFA7P9L7ncDPpEyCJf2yDKUro6xGtXhJbXZ9WU+KyXcOuX+AQ+a31BW1+g3P7iRHuwzAtrTOcDYnHArYyVP4J3RLU5hJiRCs818mPuk+dRVpJFbKU1zxOLPj4BUqX4+aVAg3XljCC58kuwbaq6C1DZIkcWn/EeBD3Llt50n8Jr2DFrzMPNWHVaiKeSQcaJcGtMPxj49ZnarhlKNr82Y3igFZ/wg=="
  ENVIRONMENT: "AgAHvVNoaMKEDDiWO5Wwid/T4v2JIV+TpQXvi0dDv0qIPh6dETfLob0sJvakWCNhG+VkauDpihGDvgyJ1PLXIg9nWxkdYQDoI52NUrzFt13VB1V/2zC+w2CjRYFeORhH+IlwLuMSlOQlE3y7xM5tLcc+Ng8j2RN0/bYnQpxDxkz0pokZY/zk/grdEulaveiw5oum6FME4HShtFMjpAiY8vgV5zveGmktUcMckXAWVCLbMUP6NydHcMW4hfdk5abucgLyyYfDZw1g0vzLMY4i7LhA4oU/vq0gWWBJOy7kZ1IkknWUq6Y2JemyR0FnVVOs7oExXXub3+94eQKSyIRUjaobuKpkgsLnhAOWM53xJsuinCsKe4TNqaGoUtsBnnBZ9sJYt5O5CuaWnUM/HQBkedMVT7QFn8QYMeR33Bw1hJuZ3jyohmWP7GdOVfVZBAMLe61EmPV7Li0Ow2xfpXCVEWCc3xLjv9dDThC/0FuaVYiEj1M4B3g7iUQPzYsd8K8QcGWFl7bmzzdasPenLVOJOxHEXtN+MdiuLn/G0lIz9POi5TcgrRyne+V01xYRITJJ7ykMLkTks2T4154e6mdnDCGt8rbzUT/TMXU2spxQ3IKdJOJFLRDVKV5pBWUp4AXSQAYIHfwWwNY9roB2+f2kR4C/l1ux0dlzcJcGlmFXHwUBPf2OOdDtIF5w8vZKgthk2hPWwEro6D2cSmEF"
  JWT_SECRET_KEY: "AgCFYrsY0s1XqnUuWzyVuklM0GVthANcJGOOQRhJge07P8hmd6W/+rbIBN8lgrvJU6/U12lS2HqgFWiBQE4f0H5qw1daXaRtF3tVqrqP6ugdVgfhwHdx5nauAvjnT5+45+8Ep951NwHCyWZydqLQ5F2bHGMPvMJfVq5qcGREhsB/dlZw1goHzQkSvBTWEDt6lgo4thPDyyNsCaEezRkBVj15HWCqPqVbjmOTt/c4R4ONdKxpipo67qVbj5VAa3G9tBdb79h7lubE2MLzPCET+f45cGiFNT08QyA7/x4U830orJzhLsjfgku7yKqlBeKdkXkmzfcF1v6Z2yjqs5UouPqfBs2CQ0ntEKWCZ2bygGMVP7wyROWpHIfdm2H7vIPeIFVifPhiSyP1C25B42YoUY6lZZJ1LilAMKKkmKoV66och/jLecuTGqfYNw+gWZIQAvZcTzdoR82Zxgx1IHugsnFzW6cdM2Trg/m9IPcdifSiN9KMOLD5Cqe2CbAoP8HnzgTrxDz+R+EiH3j6BtOEjgMRhLCf2PNMncuqhHFBuETaoFHVIYAnUrXogaxpy4Rf8IdMBzpSLbC6EjyTw/Fd9PelIqMeMJlMOYTBLyBgVLFxwK/a93uwSO9GFEZf4GFMZuWl6jS9yQSC47cEATy41iIz7dQa/nC+fdrs7qc6rSUmny6VjpVSqmpHS0MVsJGDfqwuBgaMaEe+yVsPT6GOAe3Zo+V+jUwnQmbrlHv0DkLrhEufp1dFfTC8jba0HMq27HKDdoXIN0YPpbwPaAbeyRHS3AeZPh65zBrX40PSyTMueTf3CukHMfgT/quL5agEf0sG8itA1HMYYKCBRmGv+Hu71eI2tasjwBfwVKP63T1Tx3zS/ApCynjgt6dehpG4bSJ2MIVwZnHDKTUpjUryCYBRGBPmPbK8Ge7EYBwp887J1OWt+19UXmYmy6Y/UWSZd4trihgOo6Vkusu6DyccygXWkMdHsWWHf1WxHWSd9NdoW4i3nIc0AAcbWcjeYluHHjr8Jvw3Z2OlQXEBWVdj4BPiD8nM2XQCRnXJvGOOus4A9ap3Lly0CeiRRa8uzt9JZVCQuWuhHzYKXUB5t8t00Wu5i14j68mfmJiTtfwahhaYJ+8pK4EQrtjkYwnLuqBI7XNqKbM7ZfU="
  RABBITMQ_URL: "AgBQ7yVAEDxiBfeNbvAQCJlv6egMnsqgqR+tHvcNuXScaKM/T/mD/Zx+8lHjIUknIeZehGHyn5/ayRtqqNeG/5RMV0gD1h4MyMam2EkOukFaSVqqP2vj7Q76Z882LHY7P7xMQSYdIZ4hO9g1rSa+FmldxoVVReFxOaVwu36k7lzYv/tle0cZGMs3URBKeXxIiozNYUrtLsz04Lv8bPdRaOGl7zTYc5AoTdEX6NTmnBvKFRw9Uu6V3xJLjnKqQN/ZqPRXgntdkXXeG4Q0TZ+zB/ZdG3nRFXAD2nbF3CduXYZYxnLawLC5zyARAPZhTsjh34Lpp2G3oQ2+xvKeJ+do3XHVU7eOAo9serBMPIPO+2UcvuKOPMkCPd6Lpmf4d1M8kiXAYvaIBf5jmSQmymG+QrRYF2LKdnY2g/sGHUxh1iM0E+YP5T6DlJg1AGZUvjzOefue/QKbsdqJZwE/i9X2JV1Epg9ZC/jkaDnjkDA1Ky0FZ57DnkYgr8y479s/G7a9npDJoqUQ7ggyPkk7MclJbGhJvN4p2S9gbEdDIkmkMTQYgW+jmyiR7q83gJ24JblvOPoD0UhqzCjrAbyiEBGcPZqLPx1RSKbByHI0FDNq+e4St3K8Q7JUhtzwmjdfGz6VdXb0nS8qIg+vIwQPLR2+IAnzogYhIK8Rt3qMd5SVMD86Rz+0CxjD+cXBU826Pa0Z/mEJUvnmsCVLKZl5OkaxI2v0QYECCNMH58Ia8aqoVgVB/k9B1AClCDdEiUVTExrUPpzL"