apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invoice.fullname" . }}
  labels:
    {{- include "invoice.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "invoice.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "invoice.selectorLabels" . | nindent 8 }}

    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ include "invoice.serviceAccountName" . }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "invoice.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname

      containers:
        - name: invoice-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
            - configMapRef:
                name: {{ include "invoice.fullname" . }}-config

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          # startupProbe:
          #   httpGet:
          #     path: /api/v1/invoices/health
          #     port: {{ .Values.containerPort }}
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 12  

          readinessProbe:
            httpGet:
              path: /api/v1/invoices/health
              port: {{ .Values.containerPort }}
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/v1/invoices/health
              port: {{ .Values.containerPort }}
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
