apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "auth.fullname" . }}-migrate

spec:
  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["python", "-m", "app.init_db"]

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}