apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  encryptedData:
    DATABASE_URL: <ENCRYPTED>
    JWT_SECRET_KEY: <ENCRYPTED>
    ENVIRONMENT: <ENCRYPTED>
    ACCESS_TOKEN_EXPIRE_MINUTES: <ENCRYPTED>
    RABBITMQ_URL: <ENCRYPTED>
    API_URL: <ENCRYPTED>

  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque