{{- if and .Values.secret.enabled (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order.fullname" . }}-secret
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "order.labels" . | nindent 4 }}

type: Opaque

stringData:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}