replicaCount: 3

image:
  repository: ghcr.io/kube-pod404/opslora-invoice-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

global:
  host: opslora.com

route:
  hostnames:
    - opslora.com
  path:
    type: PathPrefix
    value: /api/v1/invoices
  backend:
    name: ""
    port: 3000

secretName: invoice-secret

config:
  ORDER_SERVICE_URL: "http://opslora-order:3000"

serviceAccount:
  create: true
  name: ""

pod:
  automountServiceAccountToken: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

affinity:
  enabled: true
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral-storage: "500Mi"

probes:
  startup:
    enabled: false
    path: /api/v1/invoices/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readiness:
    enabled: true
    path: /api/v1/invoices/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    enabled: true
    path: /api/v1/invoices/health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: AgCgzftzK7ozRu7ibgLMTft1bpK2ljk0+qRnSu5wwlhDArzy4JdlXNAg/zIpNhQfTFTsGMfwG70H1dXnPvBPseLzvW5cbhp0hkaAU85H2C8h2ogt0aAwC+xjzVMG0zNtx69/bPzMc4ymA/euyc0ImFW+dYOPAuJ9V07RT1YQQxC8uKsJGkpkIxgpZBuXWUg0vxNuWKubtBop/Aai8q4WGV2NdEtpSEhUFy9IcAZDgjUV3CSi5yTZ2oEfVc9hg4fAe6WBB9BQf3k1Bila2zfkDRTTHU1Lpez62WQHLFl99Sv8GD1jwqxhyHAnHtyIb5uGl72KDCAQnmj0Ir4NWwFxl+ph9rnTS9j/Mc7OkMc1NuUJNhHHMFb7lmjq91VWWbVchY3bJTAc+som2kyT8t1H8jUrJUgLCxo8eyh/l2wbD+hnT0mEWJVI18FOkUKgMFl+P54Vxf2prg1xpj6BFjwBVoJr8ityr/uJgB2AdGpKMRXE3HQh5ZJw/PAgQyV2hIT7r/rzKpUcZa2j1oDINH7dMfZrWxXkMQMH+T/xa3hM5HGZ4BDgBmFSscezDsg0Cfo7TKeVLC+VJORTBg/XggjCa+AJFV5EhPa+8BCMtu44nZTnyb8yoCWieHP6cEPqytpWdP0KGOs8KKk0BFOmkvpGacE5+42IKngUJWKqcirNotZxJl1kc+yKfVvn6t5vMfN45WT9pZo=
  API_URL: AgDcZJNLISd89tILKzF8W7C9qe5Xmb3kSJX5Wg2JA2arfQ9OGCItHLHxBEdAEknyMaPj0tBDkemogxqm7xx6GhkaLo3Dpbyw7PwQWh6OMbYloFZWtcHrM18iJYVDAUD/0q69//ZnPm/bS9Ivi3qtGLOKhSP/TOCgCIlU2+YNM45LB6O+cIVIH7WBerf0pNKWIyzl2owjC00/WBhSCqYZ1/1OBnjItyG844CcS5AZS/+rZ1GZGY1idVT1Uyct7u/EP5EWW+EY1jVnaSXstadmJeFfspLawySr0I+8I7k2N1x2UqZacFNhL7E8Iu3ryJnOVHxq5F188YCcn9hNJb3+fwHTBs+Vp/XDg8KrnzbqH6uQ067IkzOddF7UQQQksNYtrGtlBEMQkfcMuKirKhNm4yo1TF1bKIZz3GMvmkU8J8JInySQfI5n3J499TQreXjJ9N1g+XlJbZ4vSTUqp0w7lgt4z0RC0+ymPQwI5Cs9xtI/JLBMBFc7GOh64qMFoJ6Q2NWQywpRIjjHXRYXtQ7QJbIQwKOE78ESGdB+qGTLEEVqTdWKoU0U7atiFPxo0AuazTrTFaooMDYN1w/XO18REdPobfNKjEMQLJNNOWPdORzoQm3JIzYTMLRPBf3fcT4LtY3wmd9eS3ABiUdFJRBgSrqAJwuMAMSmmgnbp7PcOD+FH92DjQMqHxBJGl+mhRCNaj8tCp32A71r
  DATABASE_URL: AgBgW/U/3e3cPlYuYiWOVfr45bZ54CgYjdyyIPo4s6kJWZC+LahF035x39BGyab5kJ1XGQ63YpEzV7gdQOmoXyQSp0tApLq1QkhbP8cPwSBDdFGJqSgTXDSnMhsiNhphTova8OXCE0vurL8G7E4MI6MChEZRjpBxAAP5h0YjtqfLyVnsXLEW5cSEeuDR1w3UMFYQsRrBydLz8DbRVfFtW2nrq3uAnRFNx2MTmIeTKYh3BBj8DX+lMLQ35G9JfAKo/DSILldsfBnFN6AmOfbtVoyx3lVS/WCFt0MbXrBpFpBaoimUCypSIE141LisW2vvK+Q9XoAT3DB6yCWkDw/LYxaYc5qkKDhC37vBqlBjG+5uNjMCJCjMklAR8p0d9VBbB6cR5f5qgR/R+m5IQTHadtx+V9YP5mLRAgLIQboBDJYNcQT9UiNhm0JBM5w5PnwXv8Nmdt+pwu3I9K7f0xcbn1vqkHs8MTg1nM3DGS5X5P/p3MDPLnKD70KpwNzZTH/Y0TB0z2uyeWHIjN4SRpZYngxaSWZDO5OG56CSphxT5An7e4KEXdgfpJrf7VnbDkieWuczCfdpHVATflaOr7HQ9itXKC8xnTx+3SejLPvF9rZb7w3KeBqsDDbQcwjT8R86DD+L1wXCRRjbUbbv+z4vs2RnjdrOeJwXH1SIdtGrXYsor2yrejZqUR7M04oOVzYdKqT743FczCbQuvDMxKkCJfsW+QM+uvB/2kbozpX0Kg43ajLuUEW6IrcMnb2DQuptjLoXCB6wcGAKPSNghGmOdKWYsaG2tA==
  ENVIRONMENT: AgB4s+M4uKJpFIJh0D0UEAzvSGrYI0lB7em73B+4OLyCAF2dfqCldEwHPYEvKgwvva4Z+irSLjkSkNYaGOebutkHojsHuk1txygoD0x+E+Q7uquOdIozhrQL8NI3d5C5lqOPENC3zMhv+S3lKS3BwZehL7mcr7sdWv3y0G72o4gipgDCBLxRKnZtLgzryBuRLW/X9NoldMzmhDMqz1KkzdGY8cYQ+USTnhAeCIKH7Kpd2lOnXTloFUO0D1FGHG/h+6oq0/l/cBA/DN95NM4QhDgBR7obraom1MhXt5Cg/fno6GUpXkwK/HPBqGVLjxAzKND/MRwiy/KBpEXub1w962JiEdHtJhV3sNaLDg6Ds94UhlpD3QVDM8MVnp4VrCaXNdVec/RBPzQYmh16pYLe7rq0uuys+dYPCYVQIyB02RGNqgQ914fqivTXuwUcmqRT7fKwviJ4EX6BDjPNGl8hFm5ozhHfb8jM50clcdLXCQ8e32ZAH9N1SBIJnT/2X3nG5tNDDsIIHBIi8qi6SKfz+O9S2JGRRCmd/Ae8st+swjewuFSMyvOtx9d873GUXdAUzv6mIijBcsl0rKXOOHGgWs/ZoEQ3zHTUXZQRUsGb3LqVaJnjQPouV6AlrzIJxJhWaH9wcXWXKPYUr+Ei+vv5bUAdyfX+YeAB8vLsOUHCyyVILeO/o/NOEL/QxBAoAG3wsACN3glKztgC571f
  JWT_SECRET_KEY: AgCB3LLQ9kWi++lInCmdnmBU/BKfvkDjU44nukcpL6g3DwG32c6B+Eiuqr82NlgiSNaKWMtnl3b7y7zeurVsnoFNbMF3+p7sE5z9FpQzh7R8Uu6AjLlH6xk1X0tBuCKhA4MFQP4S2YuHFjBM89T7YaX59AtGUgzsM21h8Hdm+lM2Tky20Y03rpkMB9aqdv8fL5ukAoA5O0QC+b6y2kXDmhoBylwwdM7HNifIN1b0hD3rjPsWugNJo7N+4KUpxLMj13TOxOEC09K9sJmmkFOwYX/DjT7/GzyyTVBk1b8ZC64HMMdZrugsZio49W1Bnjh2k8vs5s8Gtn8LTjyl6EiUBeYuy1oAiNeFKGTFMffDP4KjBfstZTPMqk0/A2OKSfVm75Pa6Ppx7hwy6D54iGTVEw8DLNW3mALlD6c6hf6iQnwcREr04V7+lM7nXMBJ5se0E2pgh9q4vX0MOLGnOfKagWD70NPgY6EHzoOkxF2Fn5OL52EU4VUmZ37lb2gmfgDICmX/zqqxVK1FFL2iPlC9k1isE6UmWIe4CPIOYxSnLHYLAsndPcigsjYfuTxEJ6V6qZanh0V5bG8pbUuwvzUK5GRg3RbFvljLTjrOETKeFecoUQpxvwZeUx9DRlNV1OCa1HESaTiqb2rwTMgde1qF/GTwQnVhCsSflg8Bb8LxMIEJAgOCZoMicMEuZwhoUTYqDucMoOrqClfxHMK81KulX9NetMLoTVN4Z5iRVWp/YqRkVNrxvFpb4vEKqFCLudOQVSBQzP+H3v6zDSK0hTe9DZYRvfeavVFg6kdhYq4gT3l4YI6SdLa30sYjkjUuiBPQj1WqHofUbUwQe6+bHpDaEZ7D9otUjXGXs5x8OG0DMiX2Yhyc32AihsiFijlTdhYV6YleeEVmzDyJSm/6Iki5hVgSqcyY3yOM/CmyLOoqlTyqDbfhoUMr/Iora4tKWktasHD+wuC6txI74IQSsUoyt28ZYuncIOLv9rI3ReCZY+HgAZNfnfCOlneU7hA76SyiNfMSqNH1LIsDi+r2fpj3ijCKI3bQVLad8prKzCJ8S5NfoSwrWWGyYEfmjI0fer2enYUHiMuBZ1Tvrl3LeTSFgTUIYr1oPAABFj9pklWJbooYsHxcyl+MlPxJCExVAazlh8x5hBsFUeY=
  RABBITMQ_URL: AgDt2SH/2sOnH5CRtvZj5IazPBRwKDLqmvK5sEAvwFhkcz15txWZ1xQqbPKaLh1x2CLrrUrQoHFfKPr21JfTHGQKf4QrhtDkrTrmUeXACN3rFwrmPT22VcdWgD+T8ciNtGPdDJZn6M3oQnddYAZAdyzmc4REt2R6fLw5/3/TNDnaKPFR8qSjEjwzGEbz/pT0sBN50X1jSF6K7OOrv2EAYDoos0Vrg8U1ptBmnziBNTzveyarkLGNdC/p+unZD52J77a+fFmgQXRYOw5Xswb9cR/HDzIH7QZbwynvekPz4/jHlXuywcR57KYMqs5qc0PaW2NE/lNyk4Xj2w3dKo67QZOHx5fTZ/4oCcGXDth2heCIDKSiv8vbTDbYHHc4akd/bRJ6zesUsoq3MvrgHBh5pbllpNWezIVkmxZY95B4UMqNDZBejVdRdq+vZ/e1yh8GiuZnkGeqHKL6TQxbJ5ctnhrJG9xYhUh0TLrZy4uptUGxk0Ddlcfw8MqgJ4lDMI0liM4C83R9jMISuahW58paxpb5iYEnooSGXbc7Nn545ez3IBU1vdo8RyVzY693nqJhruwaDaDAdbJCKwntHiicSCC3VUAFbytS/Url/1bQhfLkBR8ThJ0gfVZtZ2rhRBLCYS2xiQd4zRiKXs/l8SkQle/DsUov+AV7ZKnkemGH9X2o2BzhOq2NBxHmxFe2fFeaqHZHhkhQV1qL88mofwIG4hYWlaMsFJ8D1Pa2F4bYofiZN3xKM1OpKgUrfK+RPYgahXlu
